### ISSUE TITLE
如何使用 codeblock ? 

### ISSUE THREAD

**Issue by leobbb** [pengloo53/Hexo-theme-light_cn#3]
如何使用hexo提供的标签插件（Tag Plugins）中的 Code Block ? 

添加一个文章，并且在其中加入 {% codeblock %}  {% endcodeblock %}之后，`hexo g ` 就会报错，执行失败。

文件内容如下：

> title: Test Tag plugins
> date: 2015-10-17 11:37:42
> ---
> ### 测试 page 布局
>
> 这是使用 page 布局创建的，命令如下：
> `hexo new page "Page name"`
>
> #### 测试代码区块 
>
> 
> ```
> {% codeblock %}
> <script> 
>   var test="This is a test for display code."
>   (function(){ 
>    var tmp=45;
>   })();
> </script>
> {% codeblock %}
> ```
> 显示效果如下：
> ```
> {% codeblock %}
> <script> 
>   var test="This is a test for display code."
>   (function(){ 
>     var tmp=45;
>   })();
> </script>
> {% </codeblock %}
> ```

**Comment by pengloo53** [comment]
`codeblock`语法

```
{% codeblock [title] [lang:language] [url] [link text] %}
code snippet
{% endcodeblock %}
```
